### ISSUE TITLE
Recent changes not confirmed to work on EC2

### ISSUE THREAD

**Issue by stsievert** [stsievert/salmon#31]
Before I release v0.3, I need to check the following on EC2:

- [ ] experiment state is restored through reboot (#30)
- [ ] active algorithms start on reboot (#30)
- [x] THP are disabled (#26)
- [ ] memory swap enabled (#26)
- [ ] increase the AMI size from 32GB to 128GB (#26)
- [ ] experiments are restored (try from one AMI to another) (#30)
- [ ] refresh docs for new AMI

**Comment by stsievert** [comment]
THP is disabled ([source][1]):

```
$ grep -i HugePages_Total /proc/meminfo 
HugePages_Total:       0
```

[1]:https://access.redhat.com/solutions/46111

**Comment by stsievert** [comment]
Tracking in #32.
